### ISSUE TITLE
Just found your website, is the project dead?

### ISSUE THREAD

**Issue by awulkan** [rahularyan/tovolt#1]
I saw http://tovolt.com/ and thought it looked really interesting, but this repository is very empty. Is it abandoned?

**Comment by rahularyan** [comment]
No. I am working on it but development is very slow. Doing my best to release it as soon as possible. I will lunch few demo site before initial release. Thanks for your interests.

**Comment by awulkan** [comment]
Ok, sounds good. I hope you'll be able to pull it off. The first one to create a true Javascript alternative to Wordpress will recieve a lot of attention. I'll be waiting. :)

**Comment by hilltopmediadesign** [comment]
This is definitely a worth-while endeavor. Best of luck!
